server:
  port: 8080
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: kyn-service-gateway
  cloud:
    gateway:
      routes:
        - id: address-management
          uri: lb://address-management
          predicates:
            - Path=/api/address/**
        - id: profile-management
          uri: lb://profile-management
          predicates:
            - Path=/api/profiles/**
        - id: file-management
          uri: lb://file-management
          predicates:
            - Path=/api/files/**
        - id: authorization-server
          uri: lb://authorization-server
          predicates:
            - Path=/api/users/**
      default-filters: TokenRelay

  security:
    oauth2:
      client:
        registration:
          kyn-cloud-gateway-client:
            provider: spring
            client-id: kyn-cloud-gateway
            client-secret: 1232kyn123
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/32432f432"
            scope: openid
            client-name: kyn-cloud-gateway-client
          kyn-cloud-gateway-client-code:
            provider: spring
            client-id: kyn-cloud-gateway
            client-secret: 1232kyn123
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/authorized"
            scope: read
            client-name: kyn-cloud-gateway-client-code
        provider:
              spring:
                issuer-uri: http://auth-server:8085