server:
  port: 8080
eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: kyn-service-gateway
  cloud:
    gateway:
      routes:
        - id: address-management
          uri: lb://address-management
          predicates:
            - Path=/api/address/**
        - id: profile-management
          uri: lb://profile-management
          predicates:
            - Path=/api/profiles/**
        - id: file-management
          uri: lb://file-management
          predicates:
            - Path=/api/files/**
        - id: authorization-server
          uri: lb://authorization-server
          predicates:
            - Path=/api/users/**
      default-filters: TokenRelay

  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          kyn-cloud-gateway-client-oidc:
            provider: spring
            client-id: kyn-cloud-gateway
            client-secret: 1232kyn123
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: kyn-cloud-gateway-client-oidc
          kyn-cloud-gateway-client-authorization-code:
            provider: spring
            client-id: kyn-cloud-gateway
            client-secret: 1232kyn123
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: kyn.read,kyn.write
            client-name: kyn-cloud-gateway-client-authorization-code
          kyn-cloud-gateway-client-client-credentials:
            provider: spring
            client-id: kyn-cloud-gateway
            client-secret: 1232kyn123
            authorization-grant-type: client_credentials
            scope: kyn.read,kyn.write
            client-name: kyn-cloud-gateway-client-client-credentials
        provider:
          spring:
            issuer-uri: http://localhost:8085