server:
  port: 8080
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: kyn-service-gateway
  cloud:
    gateway:
      routes:
        - id: address-management
          uri: lb://address-management
          predicates:
            - Path=/api/address/**
        - id: profile-management
          uri: lb://profile-management
          predicates:
            - Path=/api/users/**


